# Generated by Django 5.0.1 on 2025-11-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='info', max_length=50)),
                ('color_from', models.CharField(default='blue-400', max_length=20)),
                ('color_to', models.CharField(default='blue-600', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
