# Generated by Django 5.0.1 on 2025-11-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_article_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='summary_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='summary_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_fa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='educationcard',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='educationcard',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='educationcard',
            name='description_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='educationcard',
            name='title_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='educationcard',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='educationcard',
            name='title_fa',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
